// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"AutoSaveAfterEvent","status":true,"description":"自動存檔插件 - 自動保存目前正在遊玩的存檔槽","parameters":{}},
{"name":"VampireDrain","status":true,"description":"吸血插件 - 攻擊造成傷害後依比例恢復HP","parameters":{}},
{"name":"EnemyHpBar","status":true,"description":"敵人血量條顯示","parameters":{}},
{"name":"ItemStack9999","status":false,"description":"物品堆疊上限9999","parameters":{}},
{"name":"EnemyHp100Million","status":false,"description":"敵人最大HP上限100000000","parameters":{}},
{"name":"BattleMotionSystem4","status":false,"description":"BattleMotionSystem 4.2 - 選定敵人後實際移動攻擊","parameters":{}}
];
